### ISSUE TITLE
Why default lambda_unsup set 0 in main.py if train mode

### ISSUE THREAD

**Issue by 2ndpic** [gyhandy/Group-Supervised-Learning#2]
Train GZS-Net on datasets used in paper,the command is
`python3 main.py --train True --dataset Fonts --dataset_path YOUR_LOCAL_PATH_OF_FONTS --viz_name fonts`

in main.py,know the lambda_unsup default 0, so the combine_unsup_loss is not counted in training.

Is this loss useless?

**Comment by gyhandy** [comment]
This combint_unsup_loss means we add latent feature constrain if two images have the same attribute (e.g., same id), however, this loss may eliminate the variance of attribute expression (even though the same id, the latent feature may still slightly different.) So we designed this loss but not use them in the default setting.

**Comment by 2ndpic** [comment]
Thanks for solving my doubts.

There is another problem, if there is an attribute value that is not in the training sample, for example, green has never appeared in the color attribute during training. In the inference stage, the encoder encodes the green attribute value that has not been seen before, and then exchanges the color attribute with another sample. Can the color attribute of another sample be decoded into green? 

Thank you for your time

**Comment by gyhandy** [comment]
That is a good question if the extrapolate value region can be correctly understood by model and express. I think if green is the interpolation value of the other two seen colors (e.g., red and blue), then it may be correctly understood and transferred. while if green is out of the convex boundary, it may be hard. Thanks!
