### ISSUE TITLE
模型收敛时效果并不理想

### ISSUE THREAD

**Issue by lihao1998h** [gyhandy/Group-Supervised-Learning#3]
我在Titan X上用ilab_20M训练模型后发现，当我训练约到5w轮的时候模型似乎就已经收敛，但此时效果并不好，重构图像模糊且合成的有些属性也不对，是否该代码与论文中的图片代码有所改变呢？

**Comment by gyhandy** [comment]
请问收敛的reconstruction 和 swap 的loss 大概是多少呢？ 有没有跟预训练的模型比较一下？谢谢
